name: publish a release
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'
        required: true
        default: 'v0.0.0'



jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build

  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: 'build project'
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: GH Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          make_latest: true
          files: '${{ github.workspace }}/build/libs/*.jar'
          name: 'release'
          tag_name: |
            ${{github.ref.tags == null && inputs.tag || github.ref.tags}}