name: publish a release
on:
  push:
    branches:
      - release/*
      - releases/*
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: GH Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          make_latest: true
          files: |
            build/libs/*
          tag_name: ${{ github.ref }}